title: xsixtyfour@home
email: hello@x64.coffee
description: >- # this means to ignore newlines until "baseurl:"
  Welcome to my corner of the internet where I will be sharing my insights and knowledge on topics related to IT, Security and beyond. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://x64.coffee" # the base hostname & protocol for your site, e.g. http://example.com

header_pages:
  - index.md
  - about.md

# Build settings
# theme: jekyll-theme-console
remote_theme: b2a3e8/jekyll-theme-console
plugins:
  - jekyll-feed

style: dark

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
